apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-sample-app
  description: Sample Nodejs web app
  labels:
    system: web-apps
  tags:
    - javascript
    - node
  links:
    - url: https://github.com/tdurkut/backstage-sample-app.git
      title: Backstage Sample App GitHub
      icon: code
  annotations:
    jenkins.io/job-full-name: backstage-sample-app
    github.com/project-slug: 'tdurkut/backstage-sample-app'
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: tdurkut